### ISSUE TITLE
bug from possessing a zombie

### ISSUE THREAD

**Issue by CaptainSnickerz** [StrangeOne101/Spirits#7]
[06.04 16:05:08] [Server] [WARN] java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_18_R2.entity.CraftZombie cannot be cast to class org.bukkit.entity.Player (org.bukkit.craftbukkit.v1_18_R2.entity.CraftZombie and org.bukkit.entity.Player are in unnamed module of loader java.net.URLClassLoader @65ae6ba4)
[06.04 16:05:08] [Server] [WARN] 	at Spirits-1.1.2-PK1.10.2.jar//me.numin.spirits.ability.spirit.Possess.breakDurability(Possess.java:336)
[06.04 16:05:08] [Server] [WARN] 	at Spirits-1.1.2-PK1.10.2.jar//me.numin.spirits.ability.spirit.Possess.possessionTick(Possess.java:237)
[06.04 16:05:08] [Server] [WARN] 	at Spirits-1.1.2-PK1.10.2.jar//me.numin.spirits.ability.spirit.Possess.progress(Possess.java:134)
[06.04 16:05:08] [Server] [WARN] 	at ProjectKorra-1.11.1.jar//com.projectkorra.projectkorra.ability.CoreAbility.progressAll(CoreAbility.java:277)
[06.04 16:05:08] [Server] [WARN] 	at ProjectKorra-1.11.1.jar//com.projectkorra.projectkorra.BendingManager.run(BendingManager.java:126)
[06.04 16:05:08] [Server] [WARN] 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[06.04 16:05:08] [Server] [WARN] 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[06.04 16:05:08] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1532)
[06.04 16:05:08] [Server] [WARN] 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:483)
[06.04 16:05:08] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1456)
[06.04 16:05:08] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1226)
[06.04 16:05:08] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[06.04 16:05:08] [Server] [WARN] 	at java.base/java.lang.Thread.run(Thread.java:833)
[06.04 16:05:08] [Server] [ERROR] me.numin.spirits.ability.spirit.Possess@1cea5391[
[06.04 16:05:08] [Server]   minDamage=2.0
[06.04 16:05:08] [Server]   selfDamage=6.0
[06.04 16:05:08] [Server]   damage=4.0
[06.04 16:05:08] [Server]   range=15.0
[06.04 16:05:08] [Server]   durability=6
[06.04 16:05:08] [Server]   speed=0.8
[06.04 16:05:08] [Server]   cooldown=500
[06.04 16:05:08] [Server]   duration=40000
[06.04 16:05:08] [Server]   chargeTime=0
[06.04 16:05:08] [Server]   breakingDurability=6
[06.04 16:05:08] [Server]   state=POSSESSING
[06.04 16:05:08] [Server]   pitch=0.0
[06.04 16:05:08] [Server]   volume=0.1
[06.04 16:05:08] [Server]   possessStartTime=1680793505761
[06.04 16:05:08] [Server]   releasedSneak=true
[06.04 16:05:08] [Server]   armorStand=CraftArmorStand
[06.04 16:05:08] [Server]   target=CraftZombie
[06.04 16:05:08] [Server]   spectator=me.numin.spirits.utilities.TempSpectator@1e797fae
[06.04 16:05:08] [Server]   distanceTraveled=12.000000000000002
[06.04 16:05:08] [Server]   possessString=§9** Possessed **
[06.04 16:05:08] [Server]   possessEnd=§9** Possession Ended **
[06.04 16:05:08] [Server]   possessBreak=§9** Broken Possession **
[06.04 16:05:08] [Server]   durabilityString=§9Durability{durability}
[06.04 16:05:08] [Server]   durabilityChar=⬛
[06.04 16:05:08] [Server]   player=CraftPlayer{name=CaptainSnickerz}
[06.04 16:05:08] [Server]   bPlayer=com.projectkorra.projectkorra.BendingPlayer@3376facd[
[06.04 16:05:08] [Server]   slowTime=0
[06.04 16:05:08] [Server]   player=CraftPlayer{name=CaptainSnickerz}
[06.04 16:05:08] [Server]   stance=<null>
[06.04 16:05:08] [Server]   tremorSense=true
[06.04 16:05:08] [Server]   illumination=true
[06.04 16:05:08] [Server]   chiBlocked=false
[06.04 16:05:08] [Server]   player=CraftPlayer{name=CaptainSnickerz}
[06.04 16:05:08] [Server]   uuid=9555781d-3937-49dd-92fa-1fdf9633f1ac
[06.04 16:05:08] [Server]   permaRemoved=false
[06.04 16:05:08] [Server]   toggled=true
[06.04 16:05:08] [Server]   allPassivesToggled=true
[06.04 16:05:08] [Server]   loading=false
[06.04 16:05:08] [Server]   elements=[§bWater, §3Spirit]
[06.04 16:05:08] [Server]   subelements=[§x§a§3§0§0§1§0Blood, §x§3§6§d§2§e§3Healing, §x§9§9§f§5§f§fIce, §x§0§0§8§0§4§8Plant]
[06.04 16:05:08] [Server]   abilities={6=EnergyBeam, 7=Agility, 8=Vanish, 9=Possess}
[06.04 16:05:08] [Server]   cooldowns={Possess=com.projectkorra.projectkorra.util.Cooldown@a291736}
[06.04 16:05:08] [Server]   toggledElements=[]
[06.04 16:05:08] [Server]   toggledPassives=[]
[06.04 16:05:08] [Server]   currentSlot=0
[06.04 16:05:08] [Server]   lastAccessed=1680790140777
[06.04 16:05:08] [Server]   uncacheTime=30000
[06.04 16:05:08] [Server]   uncache=<null>
[06.04 16:05:08] [Server] ]
[06.04 16:05:08] [Server]   flightHandler=com.projectkorra.projectkorra.util.FlightHandler@45c1d96a
[06.04 16:05:08] [Server]   attributeModifiers={}
[06.04 16:05:08] [Server]   attributeValues={}
[06.04 16:05:08] [Server]   started=true
[06.04 16:05:08] [Server]   removed=true
[06.04 16:05:08] [Server]   hidden=false
[06.04 16:05:08] [Server]   id=-2147466120
[06.04 16:05:08] [Server]   startTime=1680793503593
[06.04 16:05:08] [Server]   startTick=100758
[06.04 16:05:08] [Server]   attributesModified=true
[06.04 16:05:08] [Server] ]

**Comment by CaptainSnickerz** [comment]
meoh
